// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dev/internal/dao/internal"
)

// cachingDao is the data access object for the table caching.
// You can define custom methods on it to extend its functionality as needed.
type cachingDao struct {
	*internal.CachingDao
}

var (
	// Caching is a globally accessible object for table caching operations.
	Caching = cachingDao{internal.NewCachingDao()}
)

// Add your custom methods and functionality below.
