// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dev/internal/dao/internal"
)

// dataDao is the data access object for the table data.
// You can define custom methods on it to extend its functionality as needed.
type dataDao struct {
	*internal.DataDao
}

var (
	// Data is a globally accessible object for table data operations.
	Data = dataDao{internal.NewDataDao()}
)

// Add your custom methods and functionality below.
