// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dev/internal/dao/internal"
)

// devDao is the data access object for the table dev.
// You can define custom methods on it to extend its functionality as needed.
type devDao struct {
	*internal.DevDao
}

var (
	// Dev is a globally accessible object for table dev operations.
	Dev = devDao{internal.NewDevDao()}
)

// Add your custom methods and functionality below.
