// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dev/internal/dao/internal"
)

// variablesDao is the data access object for the table variables.
// You can define custom methods on it to extend its functionality as needed.
type variablesDao struct {
	*internal.VariablesDao
}

var (
	// Variables is a globally accessible object for table variables operations.
	Variables = variablesDao{internal.NewVariablesDao()}
)

// Add your custom methods and functionality below.
